# Bibliotekos

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(corrplot)
library(GGally)
library(patchwork)
library(scales)
```

# Duomenų paruošimas

```{r}

data <- read.csv("loan_data.csv")
data <- data %>%
  mutate(across(c(credit.policy, not.fully.paid, purpose), as.factor))

data <- data %>% 
  mutate(annual.inc = exp(log.annual.inc))

nrow(data)
length(data)

data %>%
  summarise(across(everything(), ~ sum(is.na(.))))
```

```{r}
set.seed(6202)
sampled_data <- data %>%
  group_by(purpose, credit.policy) %>%
  slice_sample(prop = 0.4) %>%
  ungroup()
```

```{r}
nrow(sampled_data)
head(sampled_data)
summary(sampled_data)
str(sampled_data)
```

```{r}
purpose_table <- table(sampled_data$purpose)
cp_table <- table(sampled_data$credit.policy)

purpose_cp_table <- table(sampled_data$purpose, sampled_data$credit.policy)
```

# Pirminė duomenų analizė

## Išskirtys

### Pagrindinė dalis

```{r}
count_outliers <- function(data, var_name) {
  data %>%
    summarise(
      variable = var_name,
      Q1 = quantile(.data[[var_name]], 0.25),
      Q3 = quantile(.data[[var_name]], 0.75),
      H = Q3 - Q1,
      inner_low = Q1 - 1.5*H,
      inner_high = Q3 + 1.5*H,
      outer_low = Q1 - 3*H,
      outer_high = Q3 + 3*H,
      mild_outliers = sum((.data[[var_name]] < inner_low & .data[[var_name]] > outer_low) | (.data[[var_name]] > inner_high &   .data[[var_name]] < outer_high)),
      extreme_outliers = sum(.data[[var_name]] < outer_low | .data[[var_name]] > outer_high)
      ) #%>% 
    #select(-c(inner_low, inner_high, outer_low, outer_high))
}
```

```{r}
numeric_cols <- sampled_data %>% 
  select(where(is.numeric)) %>% 
  names()

results_list <- lapply(numeric_cols, function(col) count_outliers(sampled_data, col))
outlier_summary <- bind_rows(results_list)
outlier_summary
```

```{r}
results_list <- lapply(numeric_cols, function(col) count_outliers(data, col))
outlier_summary_full <- bind_rows(results_list)
outlier_summary_full
```

```{r}
sampled_data %>%
  select(where(is.numeric)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free") +
  theme_bw() +
  theme(legend.position = "none")
```

```{r}
sampled_data %>%
  select(where(is.numeric)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "deepskyblue3", color = "honeydew3") +
  facet_wrap(~name, scales = "free") +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Reikšmė", y = "Dažnis")
```

```{r}
library(rgl)

mycolors <- c('royalblue1', 'orange1')
sampled_data$color <- mycolors[as.numeric(as.factor(sampled_data$credit.policy))]

plot3d( 
  x=sampled_data$delinq.2yrs, y=sampled_data$revol.bal, z=sampled_data$annual.inc, 
  col = sampled_data$color, 
  type = 'p',
  size = 5,
  radius = 100,
  xlab="delinq.2yrs", 
  ylab="Revol. Bal", 
  zlab="Annual Inc")
```

```{r}
print(paste("Daugiau nei vienas viešasis įrašas: ", sampled_data %>% select(pub.rec) %>% filter(pub.rec > 1) %>% nrow() ))
print(paste("Bent vienas praleistas mokėjimas: ", sampled_data %>% select(delinq.2yrs) %>% filter(delinq.2yrs > 0) %>% nrow() ))
print(paste("Palūkanos didesnės už 20%: ", sampled_data %>% select(int.rate) %>% filter(int.rate > .2) %>% nrow() ))
print(paste("Metinis uždatbis daugiau nei 1 mln.: ", sampled_data %>% select(annual.inc) %>% filter(annual.inc > 1000000) %>% nrow() ))
print(paste("Nesumokėta suma lygi 0: ", sampled_data %>% select(revol.bal) %>% filter(revol.bal == 0) %>% nrow() ))
print(paste("Daugiau nei 25 kreditoių užklausos: ", sampled_data %>% select(inq.last.6mths) %>% filter(inq.last.6mths > 25) %>% nrow() ))
```

### Daugiamatės išskirtys

```{r}
check_bounds <- function(x, col_name, info) {
  limits <- info[info$variable == col_name, ]
  as.integer(x < as.numeric(limits$outer_low) | x > as.numeric(limits$outer_high))
}
```

```{r}
data_outlier_info <- sampled_data

data_outlier_info <- sampled_data %>%
  mutate(
    across(
      all_of(numeric_cols), 
      ~ check_bounds(.x, cur_column(), outlier_summary),
      .names = "is_out_by_{.col}"
    )
  )

data_outlier_info <- data_outlier_info %>%
  mutate(outlier_dim = rowSums(across(starts_with("is_out_by_")), na.rm = TRUE)) %>%
  arrange(desc(outlier_dim))
```

```{r}
data_outlier_info <- data_outlier_info %>%
  mutate(is_outlier = as.integer(outlier_dim > 1) )
```

```{r fig.height=4, fig.width=6.5, message=FALSE, warning=FALSE}
gg_n_dim_outliers <- data_outlier_info %>%
  group_by(credit.policy, purpose) %>% 
  summarise(sum = sum(is_outlier),
            n = n(),
            value = round(sum/n, 2)) %>% 
  ggplot(aes(x = purpose, y = credit.policy, size = value, color = value)) +
  geom_point() +
  geom_text(aes(label = number(value, decimal.mark = ",")), 
            size = 4,
            color = "black",
            vjust = -3,
            show.legend = FALSE) +
  labs(x = "Paskolos paskirtis",
       y = "Atitinka kriterijus",
       title = "Daugiamačių išskirčių dalis",
       subtitle = "Paskolų smulkiam verslui grupė pasižymi daugeliu išskirčių (22 %).") +
  scale_y_discrete(labels = c("0" = "Ne", "1" = "Taip")) +
  scale_x_discrete(labels = c(
    "all_other" = "Visi kiti",
    "credit_card" = "Kredito kortelė",
    "debt_consolidation" = "Skolų konsolidavimas",
    "educational" = "Edukacinis",
    "home_improvement" = "Namų remontas",
    "major_purchase" = "Svarbus pirkimas",
    "small_business" = "Smulkus verslas"
  )) +
  scale_size(range = c(6, 20)) +
  theme_bw() +
  theme(
    panel.grid.major = element_line(
      color = "grey75",
      linetype = "dashed"
    )
  ) +
  scale_color_viridis_c(option = "plasma") +
  theme(legend.position = "none",
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1, size = 11, face = "bold"),
    axis.text.y = element_text(size = 11),
    axis.title.y = element_text(size = 12),
    axis.title.x = element_text(size = 12),
    plot.title = element_text(size = 14),
    plot.subtitle = element_text(size = 10))

gg_n_dim_outliers

#ggsave(filename = "Ekstremalių_daugimačių_išskirčių_dalis.png", width = 6.5, height = 4, units = "in", dpi = 300)
```

```{r fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
outlier_long_data <- data_outlier_info %>%
  pivot_longer(
    cols = all_of(numeric_cols),
    names_to = "name",
    values_to = "value"
  )

ggplot(outlier_long_data, aes(x = name, y = value)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(
    data = outlier_long_data %>% filter(outlier_dim > 1),
    aes(color = factor(outlier_dim)),
    size = 1.2,
    position = position_jitter(width = 0.35)
  ) +
  theme_bw() +
  facet_wrap(~name, scales = "free") +
  theme(
    legend.position = "bottom"
  ) +
  labs(color = "Išskirčių dimensija", x = NULL, y = NULL)
```

### Išskirtys pagal grupes

```{r}
outlier_summary_by_group <- sampled_data %>% 
  group_by(purpose) %>% 
  reframe(
    map_dfr(numeric_cols, ~count_outliers(pick(everything()), .x))
  )

outlier_summary_by_group
```

```{r fig.height=4, fig.width=6.5, message=FALSE, warning=FALSE}
variable_names <- c(
  "int.rate" = "Palūkanų norma",
  "annual.inc" = "Metinės pajamos",
  "dti" = "DTI rodiklis",
  "fico" = "FICO reitingas",
  "delinq.2yrs" = "Praleisti terminai",
  "pub.rec" = "Vieši įrašai",
  "revol.bal" = "Balansas",
  "inq.last.6mths" = "Užklausų skaičius",
  "days.with.cr.line" = "Dienos su limitu",
  "installment" = "Įmoka"
)

outlier_summary_by_group %>% 
  filter(extreme_outliers > 0 & variable != 'annual.inc' & variable != 'log.annual.inc') %>% 
  pull(variable) %>% 
  unique() -> variables

outlier_summary_by_group %>% 
  filter(variable %in% variables) %>% 
  select(variable, purpose, extreme_outliers) %>% 
  ggplot(aes(x = purpose, y = extreme_outliers, fill = purpose)) +
  geom_col() +
  facet_wrap(~variable,
             labeller = as_labeller(variable_names) ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, face = "bold"),
        legend.position = "none",
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 10)) +
  scale_x_discrete(labels = c(
    "all_other" = "Visi kiti",
    "credit_card" = "Kredito kortelė",
    "debt_consolidation" = "Skolų konsolidavimas",
    "educational" = "Edukacinis",
    "home_improvement" = "Namų remontas",
    "major_purchase" = "Svarbus pirkimas",
    "small_business" = "Smulkus verslas"
  )) +
  labs(title = "Išskirtys pagal paskirtį ir požymį",
       subtitle = "Diskretūs požymiai pasižymi didžiausiu išskirčių skaičiumi.",
       x = "Požymis",
       y = "Išskirčių skaičius")

#ggsave(filename = "Išskirtys_pagal_paskirtį_ir_požymį.png", width = 6.5, height = 4, units = "in", dpi = 300)
```

```{r fig.height=3.2, fig.width=6.5, message=FALSE, warning=FALSE}
hline_data <- outlier_summary %>% filter(variable %in% c("delinq.2yrs", "pub.rec", "revol.bal")) %>% 
  select(variable, extreme_outliers)

outlier_summary_by_group %>% 
  filter(variable %in% c("delinq.2yrs", "pub.rec", "revol.bal")) %>% 
  select(variable, purpose, extreme_outliers) %>% 
  ggplot(aes(x = purpose, y = extreme_outliers, fill = purpose)) +
  geom_col() +
  geom_hline(data = hline_data, aes(yintercept = extreme_outliers), 
             color = "grey15", linetype = "dashed", size = 1) +
  facet_wrap(~variable,
             labeller = as_labeller(variable_names) ) +
  scale_fill_viridis_d(option = "plasma") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8, face = "bold"),
        legend.position = "none",
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 10)) +
  scale_x_discrete(labels = c(
    "all_other" = "Visi kiti",
    "credit_card" = "Kredito kortelė",
    "debt_consolidation" = "Skolų konsolidavimas",
    "educational" = "Edukacinis",
    "home_improvement" = "Namų remontas",
    "major_purchase" = "Svarbus pirkimas",
    "small_business" = "Smulkus verslas"
  )) +
  labs(title = "Grupių išskirčių palyginimas su bendru skaičiumi",
       subtitle = "Tendencijos tarp požymių vienodos su didžiausiu išskirčių skaičiumi skolų konsolidavimo grupėje.",
       x = "Požymis",
       y = "Išskirčių skaičius")

#ggsave(filename = "Grupių išskirčių palyginimas su bendru skaičiumi.png", width = 6.5, height = 3.2, units = "in", dpi = 300)
```

### Aibių palyginimas

```{r}
out_set <- data_outlier_info %>% 
  filter(is_out_by_delinq.2yrs == 1 | is_out_by_pub.rec == 1 | is_out_by_revol.bal == 1)

in_set <- data_outlier_info %>% 
  filter(is_out_by_delinq.2yrs != 1 & is_out_by_pub.rec != 1 & is_out_by_revol.bal != 1)

```

```{r}
char_function_out <- function(data, columns){
  data %>%
    select(all_of(columns)) %>% 
    summarise(across(everything(), 
                     list(min = ~min(.x), 
                          max = ~max(.x), 
                          mean = ~mean(.x),
                          sd = ~sd(.x),
                          q25 = ~quantile(.x, 0.25),
                          median = ~median(.x),
                          q75 = ~quantile(.x, 0.75)))) %>% 
    pivot_longer(everything(), names_to = c("Variable", ".value"), names_sep = "_")
}
```

```{r}
indicators <- c("int.rate", "annual.inc", "dti", "fico")
char_out_set <- char_function_out(out_set, indicators) 
char_in_set <- char_function_out(in_set, indicators)

Variable_col <- char_out_set %>% select(Variable)
out_group_col <- data.frame(set = rep("Išskirtis", nrow(Variable_col)))
in_group_col <- data.frame(set = rep("Neišskirtis", nrow(Variable_col)))

char_out_set <- char_out_set %>% 
  select(-Variable) %>% 
  round(2) %>% 
  cbind(Variable_col, out_group_col)

char_in_set <- char_in_set %>% 
  select(-Variable) %>% 
  round(2) %>% 
  cbind(Variable_col, in_group_col)

char_of_sets <- rbind(char_out_set, char_in_set)
char_of_sets
```

```{r fig.height=4.5, fig.width=6.5, message=FALSE, warning=FALSE}
variable_names <- c(
  "int.rate" = "Palūkanų norma",
  "annual.inc" = "Metinės pajamos",
  "dti" = "DTI rodiklis",
  "fico" = "FICO reitingas"
)

bottom_part <- char_of_sets %>% 
  filter(Variable != "annual.inc") %>% 
  ggplot(aes(y = mean, x = set, color = set)) +
  geom_point(size = 3, shape = 3) +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), 
                width = 0.2, size = 0.8) +
  facet_wrap(~Variable,
             scale = "free_y",
             labeller = as_labeller(variable_names))+
  scale_y_continuous(labels = label_number(decimal.mark = ",") ) +
  theme_bw() +
  labs(x = NULL, y = NULL, color = "Duomenų poaibis") +
  theme(legend.position = "top",
        plot.margin = margin(b = 0, t = 0, r = 0, l = 0),
        legend.margin = margin(t = -10))

top_part <- char_of_sets %>% 
  filter(Variable == "annual.inc") %>% 
  ggplot(aes(y = set, x = mean, color = set)) +
  geom_point(size = 3, shape = 3) +
  scale_x_continuous(breaks = seq(0, 150000, by = 25000)) +
  geom_errorbar(aes(xmin = mean - sd, xmax = mean + sd), 
                width = 0.2, size = 0.8) +
  facet_wrap(~Variable,
             scale = "free_y",
             labeller = as_labeller(variable_names)) +
  theme_bw() +
  labs(x = "USD", y = NULL) +
  theme(legend.position = "none",
        axis.text.x = element_text(hjust = 0.8),
        axis.title.x = element_text(hjust = 1, face = "italic", size = 8),
        plot.margin = margin(b = 0, t = 0, r = 0, l = 0)) 

(top_part / bottom_part) +
  plot_layout(heights = c(1, 1.5)) +
  plot_annotation(title = "Išskirčių ir likusios imties palyginimas",
                  subtitle = "Išskirtys pasižymi vidutiniškai didesnėmis reikšmėmis išskyrus FICO reitingą.",
                  theme = theme(plot.title = element_text(size = 14),
                                plot.subtitle = element_text(size = 10) ))

#ggsave(filename = "Išskirčių ir likusios imties palyginimas.png", width = 6.5, height = 4.5, units = "in", dpi = 300)
```

## Skaitinės charakteristikos

```{r}
Modes <- function(x) {
  ux <- unique(x)
  tab <- tabulate(match(x, ux))
  ux[tab == max(tab)][1]
}
```

```{r}
char_function <- function(data, groups, columns){
  data %>%
    group_by(across({{groups}})) %>% 
    select(all_of(columns)) %>% 
    summarise(across(everything(), 
                     list(min = ~min(.x), 
                          max = ~max(.x), 
                          mean = ~mean(.x),
                          sd = ~sd(.x),
                          q25 = ~quantile(.x, 0.25),
                          median = ~median(.x),
                          q75 = ~quantile(.x, 0.75),
                          mode = ~if (cur_column() %in% c("inq.last.6mths", "delinq.2yrs", "pub.rec")){Modes(.x)} else {NA}))) %>% 
  pivot_longer(cols = -{{groups}}) %>% 
    separate(name, into = c("pozymis", "charakteristika"), sep = "_") %>%
    pivot_wider(names_from = pozymis, values_from = value)
}
```

```{r}
indicators <- c("int.rate", "installment", "annual.inc", "dti", "fico", "days.with.cr.line",
         "revol.bal", "revol.util", "inq.last.6mths", "delinq.2yrs", "pub.rec")
char_policy <- char_function(sampled_data, credit.policy, indicators) 
char_purpose <- char_function(sampled_data, purpose, indicators)
```

```{r}
char_combined <- char_function(sampled_data, c(credit.policy, purpose), indicators)
```

```{r}
char_mean <- char_combined %>% 
  select(c("credit.policy", "purpose", "charakteristika", "annual.inc")) %>% 
  filter(grepl("mean", charakteristika)) %>% 
  select(-"charakteristika")
colnames(char_mean)[3] <- "annual.inc_mean"

char_sd <- char_combined %>% 
  select(c("credit.policy", "purpose", "charakteristika", "annual.inc")) %>% 
  filter(grepl("sd", charakteristika)) %>% 
  select(-"charakteristika")
colnames(char_sd)[3] <- "annual.inc_sd"

char_median <- char_combined %>% 
  select(c("credit.policy", "purpose", "charakteristika", "annual.inc")) %>% 
  filter(grepl("median", charakteristika)) %>% 
  select(-"charakteristika")
colnames(char_median)[3] <- "annual.inc_median"

char_mean_sd <- left_join(char_mean, char_sd, by = c("purpose", "credit.policy"))
char_mean_sd_median <- left_join(char_mean_sd, char_median, by = c("purpose", "credit.policy"))
```

Naujos skaitinių charakteristikų lentelės

```{r}
char_function2 <- function(data, groups, column){
  data %>%
    group_by(across({{groups}})) %>% 
    summarise(min = min(.data[[column]]), 
              max = max(.data[[column]]), 
              mean = mean(.data[[column]]),
              sd = sd(.data[[column]]),
              q25 = quantile(.data[[column]], 0.25),
              median = median(.data[[column]]),
              q75 = quantile(.data[[column]], 0.75),
              mode = if (column %in% c("inq.last.6mths", "delinq.2yrs", "pub.rec")){Modes(.data[[column]])} else {NA}) %>%
    mutate(across(where(is.numeric), ~ round(.x, 4)))
}

numeric_variables <- sampled_data %>% 
  select(where(is.numeric)) %>% 
  names()

all_char_tables <- lapply(numeric_variables, function(variable) {
  char_function2(sampled_data, c(credit.policy, purpose), variable)})

names(all_char_tables) <- numeric_variables

all_char_tables$int.rate
int.rate_table <- char_function2(sampled_data, c(credit.policy, purpose), "int.rate")
```

```{r fig.height=5, fig.width=8, message=FALSE, warning=FALSE}
dodge_val <- position_dodge(width = 0.9)
ggplot(all_char_tables$annual.inc) +
  geom_point(aes(x = purpose, y = mean, group = credit.policy, shape = "Vidurkis"), 
             position = dodge_val, size = 3) +
  geom_errorbar(aes(x = purpose,
                    ymin = mean-sd,
                    ymax = mean+sd,
                    color = credit.policy, group = credit.policy),
                width = 0.3, size = 1, position = dodge_val) +
  geom_point(aes(x = purpose, y = median, group = credit.policy, shape = "Mediana"),
             position = dodge_val, size=2) +
  scale_shape_manual(name = "Charakteristika", 
                     values = c("Vidurkis" = 3, "Mediana" = 19)) +
  scale_y_continuous(breaks = seq(0, 228000, 38000)) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  scale_x_discrete(labels = c("Visi kiti", "Kredito kortelė", "Skolų konsolidavimas",
                              "Edukacija", "Namų remontas", "Svarbus pirkinys", "Smulkus verslas")) +
  labs(x = "Paskirtis", y = "Matinės pajamos", 
       title = "Metinės pajamos", subtitle = "Klientų negaunančių paskolos grupė, dažnai pasižymi vidutiniškai mažesnėmis pajamomis") +
  coord_flip() +
  geom_hline(yintercept = 0, size = 1, color = "grey80") +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 10),
        legend.title = element_text(size = 11,),
        legend.text = element_text(size = 10))
#ggsave(filename = "Metines_pajamos.png", width = 8, height = 5, units = "in", dpi = 300)
```

```{r}
char_credit_policy <- sampled_data %>% 
  group_by(credit.policy) %>% 
  summarise(across(where(is.numeric),
            list(mean = ~mean(.x), sd = ~sd(.x))))
char_credit_policy
```

```{r}
hist1 <- sampled_data %>% 
  mutate(credit.policy_f = factor(credit.policy, levels = c("1", "0"))) %>% 
  ggplot(aes(x = dti, fill = credit.policy_f, color = credit.policy_f)) +
  geom_histogram(position = 'identity', bins = 60, alpha = 0.75) +
  geom_vline(aes(xintercept = 13.63561), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 15.75, y = 80, label = "13,64"), size = 4, color = "red") +
  geom_vline(aes(xintercept = 12.20146), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 10, y = 80, label = "12,20"), size = 4, color = "blue") +
  labs(x = "Skolos ir pajamų santykis (DTI)", y = "Dažnis", color = "Atitinka kriterijus") +
  scale_fill_manual(name = "Atitiko kriterijus", 
                    labels = c("1" = "Taip", "0" = "Ne"), 
                    values = c("1" = "#00BFC4", "0" = "#F8766D")) +
  scale_color_manual(values = c("1" = "#00BFC4", "0" = "#F8766D"),
                     guide = "none") +
  scale_x_continuous(breaks = seq(0, 30, 5)) +
  scale_y_continuous(breaks = seq(0, 100, 20)) +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist1

hist2 <- sampled_data %>% 
  mutate(credit.policy_f = factor(credit.policy, levels = c("1", "0"))) %>% 
  ggplot(aes(x = fico, fill = credit.policy_f, color = credit.policy_f)) +
  geom_histogram(position = 'identity', bins = 40, alpha = 0.75) + 
  geom_vline(aes(xintercept = 683.0162), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 664.5, y = 250, label = "683,01"), size = 4, color = "red") +
  geom_vline(aes(xintercept = 717.8112), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 740, y = 250, label = "717,81"), size = 4, color = "blue") +
  labs(x = "FICO kredito reitingas", y = NULL, color = "Atitinka kriterijus") +
  scale_fill_manual(name = "Atitiko kriterijus", 
                    labels = c("1" = "Taip", "0" = "Ne"), 
                    values = c("1" = "#00BFC4", "0" = "#F8766D")) +
  scale_color_manual(values = c("1" = "#00BFC4", "0" = "#F8766D"),
                     guide = "none") +
  scale_x_continuous(breaks = seq(625, 850, 25)) +
  scale_y_continuous(breaks = seq(0, 300, 50)) +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist2

hist3 <- sampled_data %>% 
  mutate(credit.policy_f = factor(credit.policy, levels = c("1", "0"))) %>% 
  ggplot(aes(x = inq.last.6mths, fill = credit.policy_f, color = credit.policy_f)) +
  geom_histogram(position = 'identity', bins = 25, alpha = 0.75) + 
  geom_vline(aes(xintercept = 3.87348591), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 5.6, y = 1140, label = "3,87"), size = 4, color = "red") +
  geom_vline(aes(xintercept = 0.9883193), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 2.3, y = 1140, label = "0,99"), size = 4, color = "blue") +
  labs(x = "Užklausų skaičius per pastaruosius 6 mėn.", y = "Dažnis", color = "Atitinka kriterijus") +
  scale_fill_manual(name = "Atitiko kriterijus", 
                    labels = c("1" = "Taip", "0" = "Ne"), 
                    values = c("1" = "#00BFC4", "0" = "#F8766D")) +
  scale_color_manual(values = c("1" = "#00BFC4", "0" = "#F8766D"),
                     guide = "none") +
  scale_x_continuous(breaks = seq(0, 25, 5)) +
  scale_y_continuous(breaks = seq(0, 1500, 250)) +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist3

hist4 <- sampled_data %>% 
  mutate(credit.policy_f = factor(credit.policy, levels = c("1", "0"))) %>% 
  ggplot(aes(x = revol.util, fill = credit.policy_f, color = credit.policy_f)) +
  geom_histogram(position = 'identity', bins = 25, alpha = 0.75) + 
  geom_vline(aes(xintercept = 52.8874), color = "red", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 62, y = 170, label = "52,89"), size = 4, color = "red") +
  geom_vline(aes(xintercept = 44.7516), color = "blue", size = 1.1, linetype="dashed") +
  geom_text(aes(x = 36.5, y = 170, label = "44,75"), size = 4, color = "blue") +
  labs(x = "Atsinaujinantis panaudojimas", y = NULL, color = "Atitinka kriterijus") +
  scale_fill_manual(name = "Atitiko kriterijus", 
                    labels = c("1" = "Taip", "0" = "Ne"), 
                    values = c("1" = "#00BFC4", "0" = "#F8766D")) +
  scale_color_manual(values = c("1" = "#00BFC4", "0" = "#F8766D"),
                     guide = "none") +
  scale_x_continuous(breaks = seq(0, 100, 20)) +
  scale_y_continuous(breaks = seq(0, 200, 50)) +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        legend.position = "none")
hist4

```

```{r}
combined_hist <- (hist1 + hist2 + hist3 + hist4) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

combined_hist + plot_annotation(
  title = "Skolininkų rodiklių pasiskirstymas pagal kredito politiką",
  subtitle = "Didžiausias grupių vidurkių skirtumas matomas tarp FICO reitingo. \n(Brūkšninės vertikalios linijos žymi grupių vidurkius).",
  theme = theme(plot.title = element_text(size = 14),
                plot.subtitle = element_text(size = 10),
                legend.title = element_text(size = 11,),
                legend.text = element_text(size = 10)))
#ggsave(filename = "histogramos.png", width = 7.5, height = 6, units = "in", dpi = 300)
```

## Duomenų aibės normavimas

```{r}
min_max_normalization <- function(x){
  return((x-min(x)) / (max(x)-min(x)))
}
```

```{r}
min_max_normalized <- sampled_data %>% 
  select(where(is.numeric)) %>% 
  mutate(across(everything(), min_max_normalization))
```

```{r}
mean_sd_normalization <- function(x){
  return((x-mean(x)) / sd(x))
}
```

```{r}
mean_sd_normalized <- sampled_data %>% 
  select(where(is.numeric)) %>% 
  mutate(across(everything(), mean_sd_normalization))
```


## Koreliacijos

```{r fig.height=8, fig.width=8}
numeric_values <- mean_sd_normalized %>% 
  select(!log.annual.inc) %>%
  rename(
    "Palūkanų norma" = int.rate,
    "Įmoka" = installment, 
    "FICO" = fico,
    "DTI" = dti,
    "Dienos su paskolos limitu" = days.with.cr.line,
    "Atnaujinamas balansas" = revol.bal,
    "Atsinaujinantis panaudojimas" = revol.util,
    "Užklausos" = inq.last.6mths,
    "Praleisti terminai" = delinq.2yrs,
    "Vieši įrašai" = pub.rec,
    "Metinės pajamos" = annual.inc,
  )

#png("koreliaciju_matrica.png", width = 2000, height = 2000, res = 300)

options(OutDec = ",")
cor <- cor(numeric_values, method = "pearson")
par(mar = c(0, 0, 4, 0))
corrplot(cor, method = "circle", tl.col = "black", , type = 'lower', insig='blank',
         addCoef.col ='black', number.cex = 0.8, order = 'AOE', diag=FALSE)

mtext("Skaitinių kintamųjų koreliacijų matrica", side = 3, adj = 0, line = 2, cex = 1.17)
mtext("Didžiausia koreliacija tarp FICO ir palūkanų normos: -0,71", side = 3, adj = 0, line = 0.95, cex = 0.75)

#dev.off()
```




```{r fig.height=14, fig.width=14, message=FALSE}
scatter_matrix <- ggpairs(numeric_values,
                          title = "Sklaidos diagramų matrica",
                          axisLabels = "show",
                          lower = list(
                            continuous = wrap("points", size = 0.5, alpha = 0.3)
                          ))
scatter_matrix +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r fig.height=15, fig.width=15, message=FALSE}
numeric_values_and_policy <- sampled_data %>% 
  select(!purpose & !not.fully.paid)

scatter_matrix_cat <- ggpairs(
  numeric_values_and_policy,
  title = "Sklaidos diagramų matrica pagal kredito politiką",
  mapping = aes(color = credit.policy),
  lower = list(
    continuous = wrap("points", size = 0.5, alpha = 0.3)
  ),
  diag = list(
    continuous = wrap("densityDiag", alpha = 0.4)
  )
)

scatter_matrix_cat +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r fig.height=8, fig.width=10}
int_rate_fico <- ggplot(sampled_data, aes(x = int.rate, 
                         y = fico, 
                         color = credit.policy)) +
  geom_point(size = 1.5, alpha = 0.5) +
  #geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Palūkanų norma ir FICO reitingas",
    x = "Palūkanos",
    y = "FICO",
    color = "Kredito politika"
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)
  )

revol_bal_fico <- ggplot(sampled_data, aes(x = fico, 
                         y = revol.bal, 
                         color = credit.policy)) +
  geom_point(size = 1.5, alpha = 0.5) +
  #geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "FICO reitingas ir atnaujinamas balansas",
    x = "FICO",
    y = "Atnaujinamas balansas",
    color = "Kredito politika"
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)
  )

int_rate_revol_bal <- ggplot(sampled_data, aes(x = int.rate, 
                         y = revol.bal, 
                         color = credit.policy)) +
  geom_point(size = 1.5, alpha = 0.5) +
  #geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Palūkanų norma ir atnaujinamas balansas",
    x = "Palūkanos",
    y = "Atnaujinamas balansas",
    color = "Kredito politika"
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)
  )


installment_annual_inc <- ggplot(sampled_data, aes(x = installment, 
                         y = log.annual.inc, 
                         color = credit.policy)) +
  geom_point(size = 1.5, alpha = 0.5) +
  #geom_smooth(method = "lm", se = FALSE) + 
  labs(
    title = "Mėnesinė įmoka ir metinių pajamų logaritmas",
    x = "Įmoka",
    y = "Pajamos (log)",
    color = "Kredito politika"
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5)
  )

theme <- theme(
    legend.position = "none",
    axis.text.x = element_text(size = 11, face = "bold"),
    axis.text.y = element_text(size = 11),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    plot.title = element_text(size = 16, vjust = 1, hjust = 0.5),
    plot.subtitle = element_text(size = 10)
)

corr_plot <- (
  (int_rate_fico + revol_bal_fico) /
  (int_rate_revol_bal + installment_annual_inc)
)

corr_plot <- corr_plot +
  plot_layout(guides = "collect") &
  theme_minimal() &
  theme & 
  theme(legend.position = "bottom")

corr_plot +
  plot_annotation(
    title = "Paskolų rodiklių tarpusavio ryšiai pagal kredito politiką",
    theme = theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold"))
  )

```

```{r}
ggplot(sampled_data, aes(x = purpose, y = fico, color = as.factor(credit.policy))) +
  geom_jitter(alpha = 0.5, size = 2, width = 0.4) +
  theme_minimal() +
  labs(title = "Kredito politika pagal FICO ir paskirtį",
       x = "Paskolos paskirtis",
       y = "FICO reitingas",
       color = "Kredito politika") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r fig.height=8, fig.width=12}
long_data <- sampled_data %>%
  pivot_longer(
    cols = c(fico, int.rate, log.annual.inc, dti),
    names_to = "Rodiklis",
    values_to = "Reiksme"
  ) %>% 
  mutate(Rodiklis = factor(Rodiklis, 
                           levels = c("fico", "int.rate", "log.annual.inc", "dti"),
                           labels = c("FICO reitingas", "Palūkanų norma", "Metinės pajamos (log)", "DTI rodiklis")))

ggplot(long_data, aes(x = purpose, y = Reiksme, color = as.factor(credit.policy))) +
  geom_jitter(alpha = 0.5, size = 1.25, width = 0.3) +
  stat_summary(
    fun.min = min,
    fun.max = max,
    geom = "errorbar",
    position = position_dodge(width = 0.5),
    width = 0.4,
    size = 0.8
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) + 
  facet_wrap(~ Rodiklis, scales = "free_y") +
  scale_x_discrete(labels = c("Visi kiti", "Kredito kortelė", "Skolų konsolidavimas",
                              "Edukacija", "Namų remontas", "Svarbus pirkinys", "Smulkus verslas")) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1, size = 11, face = "bold"),
    axis.text.y = element_text(size = 11),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10),
    strip.text = element_text(size = 12, face = "bold")) +
  labs(
    title = "Kredito politika pagal skirtingus rodiklius ir paskirtį",
    x = "Paskolos paskirtis",
    y = "Reikšmė",
    color = "Kredito politika"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom"
  )
```


## Papildomos vizualizacijos

### Kredito politikos atitikimas pagal paskolos paskirtį

```{r fig.height=6, fig.width=10}
ggplot(sampled_data,
       aes(x = purpose, fill = factor(credit.policy))) +
  geom_bar(position = "fill") +
  labs(
    title = "Kredito politikos atitikimas pagal paskolos paskirtį",
    x = "Paskolos paskirtis",
    y = "Dalis",
    fill = "Kredito politika"
  ) +
  scale_color_discrete(name = "Atitinka kriterijus", labels = c("Ne","Taip")) +
  scale_x_discrete(labels = c("Visi kiti", "Kredito kortelė", "Skolų konsolidavimas",
                              "Edukacija", "Namų remontas", "Svarbus pirkinys", "Smulkus verslas")) +
  theme_minimal() + 
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1, size = 11, face = "bold"),
    axis.text.y = element_text(size = 11),
    axis.title.y = element_text(size = 12, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10),
    strip.text = element_text(size = 12, face = "bold"),
    legend.position = "bottom")
```

```{r}
ggplot(sampled_data,
       aes(x = purpose,
           y = fico,
           fill = factor(credit.policy))) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  labs(
    title = "FICO pasiskirstymas pagal paskolos paskirtį ir kredito politiką",
    x = "Paskolos paskirtis",
    y = "FICO",
    fill = "Kredito politika"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom"
  )
```
